package com.example.takanimali.navigation

const val ROUTE_HOME = "home"
const val ROUTE_LOGIN = "login"
const val ROUTE_REGISTER = "register"
const val ROUTE_PROFILE = "profile"
const val ROUTE_POINTS = "points"
const val ROUTE_COLLECTION = "collection"
const val ROUTE_HISTORY = "history"
const val ROUTE_PROFILE_DETAILS = "profile_details"
const val ROUTE_CHANGE_PASSWORD = "change_password"
const val ROUTE_HELP = "help"
const val ROUTE_REPORT = "report"
const val ROUTE_COLLECT = "collect"
const val ROUTE_TERMS = "terms"